package com.assurant.brain.jira;

import com.assurant.brain.dto.request.ProposedTicket;
import com.assurant.brain.jobs.AsyncJobService;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Log4j2
@Service
@RequiredArgsConstructor
public class TicketCreationService {

    static final String FAILED_PREFIX = "FAILED:";

    private final JiraClient jiraClient;
    private final AsyncJobService asyncJobService;

    @Async("brainLlmExecutor")
    public void createTicketsAsync(String projectKey, List<ProposedTicket> tickets, UUID jobId) {
        try {
            asyncJobService.markRunning(jobId, "Creating " + tickets.size() + " ticket(s) in " + projectKey);
            List<String> createdKeys = createTickets(projectKey, tickets, jobId);
            long failed = createdKeys.stream().filter(k -> k.startsWith(FAILED_PREFIX)).count();
            Map<String, Object> result = Map.of(
                    "projectKey", projectKey,
                    "createdKeys", createdKeys,
                    "count", createdKeys.size(),
                    "failed", failed);
            if (failed > 0) {
                asyncJobService.markPartial(jobId, result);
            } else {
                asyncJobService.markSucceeded(jobId, result);
            }
        } catch (Exception e) {
            log.error("Async ticket creation job={} failed: {}", jobId, e.getMessage(), e);
            asyncJobService.markFailed(jobId,
                    e.getMessage() != null ? e.getMessage() : e.getClass().getSimpleName());
        }
    }

    public List<String> createTickets(String projectKey, List<ProposedTicket> tickets) {
        return createTickets(projectKey, tickets, null);
    }

    public List<String> createTickets(String projectKey, List<ProposedTicket> tickets, UUID jobId) {
        List<String> createdKeys = new ArrayList<>();
        int total = tickets.size();
        int done = 0;

        for (ProposedTicket ticket : tickets) {
            Map<String, Object> fields = Map.of(
                    "project", Map.of("key", projectKey),
                    "summary", ticket.title(),
                    "description", buildAdfDescription(ticket),
                    "issuetype", Map.of("name", ticket.issueType()),
                    "priority", Map.of("name", ticket.priority())
            );

            try {
                Map<String, Object> response = jiraClient.createIssue(fields);
                String key = (String) response.get("key");
                createdKeys.add(key);
                log.info("Created Jira ticket {} for '{}'", key, ticket.title());
            } catch (Exception e) {
                log.error("Failed to create Jira ticket '{}': {}", ticket.title(), e.getMessage());
                createdKeys.add(FAILED_PREFIX + ticket.title());
            }
            done++;
            if (jobId != null) {
                int pct = (int) Math.floor(100.0 * done / total);
                asyncJobService.updateProgress(jobId, pct,
                        "Created " + done + "/" + total + " in " + projectKey);
            }
        }

        return createdKeys;
    }

    private Map<String, Object> buildAdfDescription(ProposedTicket ticket) {
        List<Object> content = new ArrayList<>();

        if (ticket.description() != null && !ticket.description().isBlank()) {
            content.add(Map.of("type", "paragraph",
                    "content", List.of(Map.of("type", "text", "text", ticket.description()))));
        }

        if (ticket.acceptanceCriteria() != null && !ticket.acceptanceCriteria().isBlank()) {
            content.add(Map.of("type", "paragraph",
                    "content", List.of(
                            Map.of("type", "text", "text", "Acceptance Criteria:",
                                    "marks", List.of(Map.of("type", "strong")))
                    )));
            content.add(Map.of("type", "paragraph",
                    "content", List.of(Map.of("type", "text", "text", ticket.acceptanceCriteria()))));
        }

        content.add(Map.of("type", "paragraph",
                "content", List.of(Map.of("type", "text", "text",
                        "Story Points: " + ticket.storyPoints() + " | Generated by Project Brain"))));

        return Map.of("version", 1, "type", "doc", "content", content);
    }
}
