package com.assurant.brain.github;

import com.assurant.brain.util.GitHubUrlParser;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.stereotype.Service;

import java.util.Map;

@Log4j2
@Service
@RequiredArgsConstructor
public class PrCreationService {

    private static final String BRANCH_PREFIX = "brain/";

    private final GitHubClient gitHubClient;

    public PrResult createPullRequest(String repoUrl, String baseBranch,
                                       Map<String, String> generatedFiles, String planSummary) {
        return createPullRequest(repoUrl, baseBranch, generatedFiles, planSummary,
                buildPrBody(generatedFiles, planSummary));
    }

    public PrResult createPullRequest(String repoUrl, String baseBranch,
                                       Map<String, String> generatedFiles, String planSummary,
                                       String prBody) {
        return createPullRequest(repoUrl, baseBranch, generatedFiles, planSummary, prBody, null);
    }

    public PrResult createPullRequest(String repoUrl, String baseBranch,
                                       Map<String, String> generatedFiles, String planSummary,
                                       String prBody, String jiraIssueKey) {
        GitHubUrlParser.OwnerRepo ownerRepo = GitHubUrlParser.parse(repoUrl);
        String branchName = BRANCH_PREFIX + "codegen-" + System.currentTimeMillis();

        log.info("Creating PR for {}/{} branch={} with {} files",
                ownerRepo.owner(), ownerRepo.repo(), branchName, generatedFiles.size());

        String baseSha = gitHubClient.getDefaultBranchSha(ownerRepo.owner(), ownerRepo.repo(), baseBranch);
        gitHubClient.createBranch(ownerRepo.owner(), ownerRepo.repo(), branchName, baseSha);

        for (Map.Entry<String, String> entry : generatedFiles.entrySet()) {
            gitHubClient.createOrUpdateFile(
                    ownerRepo.owner(), ownerRepo.repo(), branchName,
                    entry.getKey(), entry.getValue(),
                    "brain: generate " + entry.getKey()
            );
        }

        String prefix = jiraIssueKey == null || jiraIssueKey.isBlank()
                ? "brain: "
                : "[" + jiraIssueKey + "] brain: ";
        String prTitle = prefix + truncate(planSummary, 60);

        GitHubClient.PullRequestResult result = gitHubClient.createPullRequest(
                ownerRepo.owner(), ownerRepo.repo(), prTitle, prBody, branchName, baseBranch
        );

        return new PrResult(branchName, result.prNumber(), result.prUrl());
    }

    private String truncate(String text, int maxLength) {
        if (text == null || text.length() <= maxLength) return text;
        return text.substring(0, maxLength - 3) + "...";
    }

    private String buildPrBody(Map<String, String> files, String planSummary) {
        StringBuilder body = new StringBuilder();
        body.append("## Generated by Project Brain\n\n");
        body.append("This PR was auto-generated based on a fully clarified implementation plan.\n\n");
        body.append("### Plan Summary\n\n");
        body.append(planSummary).append("\n\n");
        body.append("### Files Generated\n\n");
        files.keySet().forEach(f -> body.append("- `").append(f).append("`\n"));
        body.append("\n### Self-Review\n\n");
        body.append("This code passed automated self-review before PR creation.\n\n");
        body.append("---\n\n");
        body.append("**This is a Draft PR.** Human review is required before merging.\n");
        return body.toString();
    }

    public record PrResult(String branchName, int prNumber, String prUrl) {}
}
