package com.assurant.brain.codegen;

import com.assurant.brain.avenger.MirageReviewer;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

@Log4j2
@Service
@RequiredArgsConstructor
public class PrDescriptionRenderer {

    public record PrAnnotations(
            Map<String, String> previousFiles,
            Map<String, String> generatedFiles,
            Set<String> readOnlyReferences,
            List<String> conventionsEnforced,
            MirageReviewer.Report mirageReport,
            List<SeamAnalyzer.CallerSite> blastRadius,
            int testsAdded,
            int linesCovered,
            String rationale,
            String planSummary) {}

    public String render(PrAnnotations annotations) {
        StringBuilder body = new StringBuilder();

        body.append("## Generated by Project Brain\n\n");
        body.append("Auto-generated against a fully clarified plan, AST-validated, symbol-grounded, ")
            .append("boundary-enforced, sandbox-compiled, and reviewed by the Avenger panel before ")
            .append("the PR opened. Verify the **Scope** and **Style fingerprint** sections — they ")
            .append("answer 90% of review questions without you reading the diff.\n\n");

        body.append("### Scope\n\n");
        renderScope(body, annotations);

        body.append("\n### Read-only references\n\n");
        renderReadOnly(body, annotations);

        body.append("\n### Conventions enforced\n\n");
        renderConventions(body, annotations);

        body.append("\n### Style fingerprint comparison\n\n");
        renderMirage(body, annotations);

        body.append("\n### Symbol grounding\n\n");
        renderGrounding(body, annotations);

        body.append("\n### Blast radius\n\n");
        renderBlastRadius(body, annotations);

        body.append("\n### Test coverage delta\n\n");
        renderTestDelta(body, annotations);

        body.append("\n### Rationale\n\n");
        body.append(annotations.rationale() == null || annotations.rationale().isBlank()
                ? "(none provided)\n"
                : annotations.rationale().trim() + "\n");

        body.append("\n---\n\n**Draft PR.** Human review required before merging.\n");
        return body.toString();
    }

    private void renderScope(StringBuilder body, PrAnnotations a) {
        Set<String> touched = new TreeSet<>(a.generatedFiles().keySet());
        body.append(touched.size()).append(" file(s) modified:\n");
        for (String path : touched) {
            int delta = lineDelta(a.previousFiles(), path, a.generatedFiles().get(path));
            body.append("  - `").append(path).append("` (")
                .append(delta >= 0 ? "+" : "")
                .append(delta).append(" lines)\n");
        }
    }

    private void renderReadOnly(StringBuilder body, PrAnnotations a) {
        if (a.readOnlyReferences() == null || a.readOnlyReferences().isEmpty()) {
            body.append("(none — change is self-contained)\n");
            return;
        }
        for (String ref : new TreeSet<>(a.readOnlyReferences())) {
            body.append("  - `").append(ref).append("`\n");
        }
    }

    private void renderConventions(StringBuilder body, PrAnnotations a) {
        if (a.conventionsEnforced() == null || a.conventionsEnforced().isEmpty()) {
            body.append("(no convention checks recorded)\n");
            return;
        }
        for (String c : a.conventionsEnforced()) {
            body.append("  ✓ ").append(c).append("\n");
        }
    }

    private void renderMirage(StringBuilder body, PrAnnotations a) {
        MirageReviewer.Report r = a.mirageReport();
        if (r == null) {
            body.append("(MIRAGE did not run — baseline unavailable)\n");
            return;
        }
        body.append("Verdict: **").append(r.verdict().name()).append("**\n");
        if (r.signals() == null || r.signals().isEmpty()) {
            body.append("All style signals within ±1σ of project baseline.\n");
        } else {
            body.append("Signals out of band:\n");
            for (String s : r.signals()) body.append("  - ").append(s).append("\n");
        }
    }

    private void renderGrounding(StringBuilder body, PrAnnotations a) {
        body.append("All symbol references resolved against project graph (FORGE + SymbolGroundingValidator).\n");
    }

    private void renderBlastRadius(StringBuilder body, PrAnnotations a) {
        if (a.blastRadius() == null || a.blastRadius().isEmpty()) {
            body.append("0 callers across the project graph — risk: **LOW**\n");
            return;
        }
        Map<String, Long> byProject = new java.util.TreeMap<>();
        for (SeamAnalyzer.CallerSite c : a.blastRadius()) {
            byProject.merge(c.projectId() == null ? "(unknown)" : c.projectId(), 1L, Long::sum);
        }
        long total = a.blastRadius().size();
        String risk = total >= 10 ? "**HIGH** (≥10 callers)"
                : total >= 3 ? "**MEDIUM**" : "**LOW**";
        body.append(total).append(" caller(s) — risk: ").append(risk).append("\n");
        byProject.forEach((p, n) ->
                body.append("  - ").append(n).append(" in `").append(p).append("`\n"));
    }

    private void renderTestDelta(StringBuilder body, PrAnnotations a) {
        body.append("+").append(a.testsAdded()).append(" new test(s), +")
            .append(a.linesCovered()).append(" lines covered\n");
    }

    private int lineDelta(Map<String, String> previous, String path, String generated) {
        String prev = previous == null ? "" : previous.getOrDefault(path, "");
        int prevLines = prev.isBlank() ? 0 : prev.split("\n", -1).length;
        int genLines = generated == null || generated.isBlank() ? 0 : generated.split("\n", -1).length;
        return genLines - prevLines;
    }
}
