package com.assurant.brain.sage;

public enum BrainInputEventType {
    PROJECT_INGESTION,
    REQUIREMENT_ANALYSIS,
    AUTODEV_KICKOFF,
    JIRA_WEBHOOK,
    DOCUMENT_INTAKE,
    TICKET_PROPOSAL,
    INCIDENT_EXPLANATION,
    DOC_GENERATION,
    RULE_PACK_INSTALL,
    CI_REMEDIATION,
    AVENGERS_FULL_REVIEW
}
