package com.assurant.brain.enums;

public enum LlmOperation {
    CLARIFY, PLAN, EXPLAIN, CODE_GENERATE, CODE_REVIEW, CODE_FIX,
    DOC_GENERATE, TICKET_PROPOSE, CI_PARSE, IMAGE_ANALYZE, MERGE_ANALYZE,
    AVENGER_REVIEW,
    MULTI_REPO_DETECT,
    MULTI_REPO_PLAN,
    COMMUNITY_SUMMARY,
    RERANK_SCORING,
    GROUNDING_CHECK
}
